DELETE FROM mpa;
ALTER TABLE mpa ALTER COLUMN id RESTART WITH 1;

DELETE FROM genre;
ALTER TABLE genre ALTER COLUMN id RESTART WITH 1;

DELETE FROM friends;
ALTER TABLE friends ALTER COLUMN id RESTART WITH 1;

DELETE FROM "like";
ALTER TABLE "like" ALTER COLUMN id RESTART WITH 1;

DELETE FROM film_genre;
ALTER TABLE film_genre ALTER COLUMN id RESTART WITH 1;

DELETE FROM "user";
ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1;

DELETE FROM film;
ALTER TABLE film ALTER COLUMN id RESTART WITH 1;

DELETE FROM film_director;
ALTER TABLE film_director ALTER COLUMN id RESTART WITH 1;

DELETE FROM director;
ALTER TABLE director ALTER COLUMN id RESTART WITH 1;

DELETE FROM feed;
ALTER TABLE feed ALTER COLUMN id RESTART WITH 1;

INSERT INTO mpa (name) VALUES
('G'),
('PG'),
('PG-13'),
('R'),
('NC-17');

INSERT INTO genre (name) VALUES
('Комедия'),
('Драма'),
('Мультфильм'),
('Триллер'),
('Документальный'),
('Боевик');