package ru.yandex.practicum.filmorate.exception;

public enum ExceptionType {
    INVALID_LOGIN,
    USER_NOT_FOUND,
    FILM_NOT_FOUND,
    GENRE_NOT_FOUND,
    DIRECTOR_NOT_FOUND,
    MPA_NOT_FOUND,
    INVALID_FILM_RELEASE_DATE,
    INVALID_FILM_DESCRIPTION,
    INVALID_SORT_ORDER,
    USER_LIKE_ALREADY_EXISTS,
    USER_LIKE_NOT_EXISTS,
    INVALID_FRIENDSHIP_ADD,
    INVALID_FRIENDSHIP_REMOVE,
    REQUIRED_FIELD_MISSING,
    REVIEW_NOT_FOUND,
    REVIEW_FEEDBACK_ALREADY_EXISTS,
    REVIEW_FEEDBACK_NOT_EXISTS,
    UNEXPECTED_ERROR
}
